import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const PixelifyBold = localFont({
  src: './fonts/PixelifyBold.ttf',
  variable: '--font-Pixelify-Bold',
  weight: '100 900',
});
const PixelifyRegular = localFont({
  src: './fonts/PixelifyRegular.ttf',
  variable: '--font-Pixelify-Regular',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${PixelifyBold.variable} ${PixelifyRegular.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
